### ISSUE TITLE
try to deploy cluster mode 

### ISSUE THREAD

**Issue by dannyZhou** [WeBankFinTech/FATE#135]
**Describe the bug**
```
==> python/logs/processor-50002.log <==
Exception calling application: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/data/projects/fate/python/arch/processor/processor.py", line 57, in get_function
    return cloudpickle.loads(function_bytes)
  File "/data/projects/fate/python/federatedml/toy_example/secure_add_host.py", line 21, in <module>
    from federatedml.util.transfer_variable import SecureAddExampleTransferVariable
  File "/data/projects/fate/python/federatedml/util/__init__.py", line 21, in <module>
    from federatedml.util.param_checker import DataIOParamChecker
  File "/data/projects/fate/python/federatedml/util/param_checker.py", line 28, in <module>
    LOGGER = log_utils.getLogger()
  File "/data/projects/fate/python/arch/api/utils/log_utils.py", line 94, in getLogger
    frame = inspect.stack()[1]
  File "/data/projects/common/miniconda3/lib/python3.6/inspect.py", line 1494, in stack
    return getouterframes(sys._getframe(1), context)
  File "/data/projects/common/miniconda3/lib/python3.6/inspect.py", line 1471, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/data/projects/common/miniconda3/lib/python3.6/inspect.py", line 1441, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/data/projects/common/miniconda3/lib/python3.6/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/data/projects/common/miniconda3/lib/python3.6/inspect.py", line 725, in getmodule
    file = getabsfile(object, _filename)
  File "/data/projects/common/miniconda3/lib/python3.6/inspect.py", line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/data/projects/fate/venv/lib/python3.6/posixpath.py", line 376, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/projects/fate/venv/lib/python3.6/site-packages/grpc/_server.py", line 389, in _call_behavior
    return behavior(argument, context), True
  File "/data/projects/fate/python/arch/processor/processor.py", line 111, in mapValues
    _mapper, _serdes = self.get_function_and_serdes(task_info)
  File "/data/projects/fate/python/arch/processor/processor.py", line 233, in get_function_and_serdes
    return self.get_function(_function_bytes), self._serdes
  File "/data/projects/fate/venv/lib/python3.6/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/data/projects/fate/python/arch/processor/processor.py", line 60, in get_function
    return pickle._loads(function_bytes)
  File "/data/projects/common/miniconda3/lib/python3.6/pickle.py", line 1558, in _loads
    encoding=encoding, errors=errors).load()
  File "/data/projects/common/miniconda3/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/data/projects/common/miniconda3/lib/python3.6/pickle.py", line 1347, in load_stack_global
    self.append(self.find_class(module, name))
  File "/data/projects/common/miniconda3/lib/python3.6/pickle.py", line 1388, in find_class
    __import__(module, level=0)
  File "/data/projects/fate/python/federatedml/toy_example/secure_add_host.py", line 21, in <module>
    from federatedml.util.transfer_variable import SecureAddExampleTransferVariable
  File "/data/projects/fate/python/federatedml/util/__init__.py", line 21, in <module>
    from federatedml.util.param_checker import DataIOParamChecker
  File "/data/projects/fate/python/federatedml/util/param_checker.py", line 28, in <module>
    LOGGER = log_utils.getLogger()
  File "/data/projects/fate/python/arch/api/utils/log_utils.py", line 94, in getLogger
    frame = inspect.stack()[1]
  File "/data/projects/common/miniconda3/lib/python3.6/inspect.py", line 1494, in stack
    return getouterframes(sys._getframe(1), context)
  File "/data/projects/common/miniconda3/lib/python3.6/inspect.py", line 1471, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/data/projects/common/miniconda3/lib/python3.6/inspect.py", line 1441, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/data/projects/common/miniconda3/lib/python3.6/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/data/projects/common/miniconda3/lib/python3.6/inspect.py", line 725, in getmodule
    file = getabsfile(object, _filename)
  File "/data/projects/common/miniconda3/lib/python3.6/inspect.py", line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/data/projects/fate/venv/lib/python3.6/posixpath.py", line 376, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

```

**Comment by dannyZhou** [comment]
Another excpetion is:

Tutorial: https://github.com/WeBankFinTech/FATE/tree/master/cluster-deploy
when I run 
```
export PYTHONPATH=/data/projects/fate/python 
source /data/projects/fate/venv/bin/activate
cd /data/projects/fate/python/examples/toy_example/
sh run_toy_examples_standalone.sh
``` 
 It shows success.

However I run
```
export PYTHONPATH=/data/projects/fate/python 
source /data/projects/fate/venv/bin/activate
cd /data/projects/fate/python/examples/toy_example/
 sh run_toy_example_cluster.sh host job_1 1000 999
sh run_toy_example_cluster.sh guest job_1 1000 999
``` 


(venv) [app@e1ff17e6162d fate]$ cd python/logs/
(venv) [app@e1ff17e6162d logs]$ ls
123  toy_example_20190429125615
(venv) [app@e1ff17e6162d logs]$ cat 
123/                        toy_example_20190429125615/ 
(venv) [app@e1ff17e6162d logs]$ cat 123/
eggroll.log                  status_tracer_decorator.log  
(venv) [app@e1ff17e6162d logs]$ cat 123/eggroll.log 
"2019-04-29 12:56:46,012 - eggroll.py[line:160] - DEBUG: created table: type:LMDB namespace:123 name:__federation__ partitions:10"
"2019-04-29 12:56:48,491 - eggroll.py[line:177] - DEBUG: created table: type:IN_MEMORY namespace:123 name:3e99101c-6a7e-11e9-b2e0-0242ac110002 partitions:1"
"2019-04-29 12:56:51,870 - eggroll.py[line:160] - DEBUG: created table: type:LMDB namespace:123 name:__federation__ partitions:10"
"2019-04-29 12:56:52,520 - eggroll.py[line:177] - DEBUG: created table: type:IN_MEMORY namespace:123 name:4216fbdc-6a7e-11e9-bb5a-0242ac110002 partitions:1"
(venv) [app@e1ff17e6162d logs]$ cat 123/status_tracer_decorator.log 
"2019-04-29 12:56:49,725 - status_tracer_decorator.py[line:73] - INFO: job status is failed"
"2019-04-29 12:56:49,726 - status_tracer_decorator.py[line:74] - INFO: Traceback (most recent call last):
  File "/data/projects/fate/python/workflow/status_tracer_decorator.py", line 69, in wrapper
    res = func(self, *args, **kwargs)
  File "../../workflow/toy_example_workflow/secure_add_host_workflow.py", line 66, in run
    self.secure_add_host_inst.run()
  File "/data/projects/fate/python/federatedml/toy_example/secure_add_host.py", line 68, in run
    self.secure()
  File "/data/projects/fate/python/federatedml/toy_example/secure_add_host.py", line 39, in secure
    y_shares = self.y.mapValues(self.share)
  File "/data/projects/fate/python/arch/api/cluster/eggroll.py", line 109, in mapValues
    return _EggRoll.get_instance().map_values(self, func)
  File "/data/projects/fate/python/arch/api/cluster/eggroll.py", line 302, in map_values
    resp = self.proc_stub.mapValues(unary_p)
  File "/data/projects/fate/venv/lib/python3.6/site-packages/grpc/_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/data/projects/fate/venv/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "172.17.0.2:8011: com.webank.ai.fate.core.error.exception.MultipleRuntimeThrowables: error occured in sub tasks. processor type: MapValuesServiceProcessor
	at com.webank.ai.fate.eggroll.roll.api.grpc.server.RollProcessServiceImpl$ProcessServiceTemplate.run(RollProcessServiceImpl.java:324)
	at com.webank.ai.fate.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:51)
	at com.webank.ai.fate.eggroll.roll.api.grpc.server.RollProcessServiceImpl.mapValues(RollProcessServiceImpl.java:115)
	at com.webank.ai.fate.api.eggroll.processor.ProcessServiceGrpc$MethodHandlers.invoke(ProcessServiceGrpc.java:626)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Throwable: idx: 0
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.webank.ai.fate.eggroll.roll.api.grpc.client.EggProcessServiceClient.unaryProcessToStorageLocatorUnaryCall(EggProcessServiceClient.java:146)
	at com.webank.ai.fate.eggroll.roll.api.grpc.client.EggProcessServiceClient.mapValues(EggProcessServiceClient.java:57)
	at com.webank.ai.fate.eggroll.roll.service.async.processor.MapValuesServiceProcessor.call(MapValuesServiceProcessor.java:35)
	at com.webank.ai.fate.eggroll.roll.service.async.processor.MapValuesServiceProcessor.call(MapValuesServiceProcessor.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at com.webank.ai.fate.core.api.grpc.client.GrpcStreamingClientTemplate.calleeStreamingRpcWithImmediateDelayedResult(GrpcStreamingClientTemplate.java:153)
	at com.webank.ai.fate.eggroll.roll.api.grpc.client.EggProcessServiceClient.unaryProcessToStorageLocatorUnaryCall(EggProcessServiceClient.java:144)
	... 7 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	... 3 more
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.17.0.2:50001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: java.net.ConnectException: Connection refused
	... 11 more

**Comment by dannyZhou** [comment]
See https://github.com/grpc/grpc/issues/12116
