### ISSUE TITLE
[cluster version]toy example failed

### ISSUE THREAD

**Issue by sukkiCat** [WeBankFinTech/FATE#254]
**Describe the bug**

**To Reproduce**
1. in host party:
    cd /data/projects/fate/python/examples/toy_example;
    bash run_toy_example_cluster.sh host test_0624_1 11 9;
2. in guest party:
    cd /data/projects/fate/python/examples/toy_example;
    bash run_toy_example_cluster.sh guest test_0624_1 11 9;
3. error occured: 
    jobid is test_0624_1
Running...
Finish, time cost is 0.0453
Secure Add Example Task Is FAIL!!!

**Screenshots**
task log in guest:
![image](https://user-images.githubusercontent.com/30313245/59999252-18fbeb80-9694-11e9-82da-c3a2c9ddd03b.png)
task log in host:
![image](https://user-images.githubusercontent.com/30313245/59999296-34ff8d00-9694-11e9-8694-fc5c6b6101ec.png)

**error log in host**
"2019-06-24 15:07:55,561 - status_tracer_decorator.py[line:73] - INFO: job status is failed"
"2019-06-24 15:07:55,561 - status_tracer_decorator.py[line:74] - INFO: Traceback (most recent call last):
  File "/data/projects/fate/python/workflow/status_tracer_decorator.py", line 69, in wrapper
    res = func(self, *args, **kwargs)
  File "../../workflow/toy_example_workflow/secure_add_host_workflow.py", line 66, in run
    self.secure_add_host_inst.run()
  File "/data/projects/fate/python/federatedml/toy_example/secure_add_host.py", line 68, in run
    self.secure()
  File "/data/projects/fate/python/federatedml/toy_example/secure_add_host.py", line 39, in secure
    y_shares = self.y.mapValues(self.share)
  File "/data/projects/fate/python/arch/api/cluster/eggroll.py", line 109, in mapValues
    return _EggRoll.get_instance().map_values(self, func)
  File "/data/projects/fate/python/arch/api/cluster/eggroll.py", line 302, in map_values
    resp = self.proc_stub.mapValues(unary_p)
  File "/data/projects/common/miniconda3/lib/python3.6/site-packages/grpc/_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/data/projects/common/miniconda3/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "172.16.0.9:8011: com.webank.ai.fate.core.error.exception.MultipleRuntimeThrowables: error occured in sub tasks. processor type: MapValuesServiceProcessor
	at com.webank.ai.fate.eggroll.roll.api.grpc.server.RollProcessServiceImpl$ProcessServiceTemplate.run(RollProcessServiceImpl.java:324)
	at com.webank.ai.fate.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:51)
	at com.webank.ai.fate.eggroll.roll.api.grpc.server.RollProcessServiceImpl.mapValues(RollProcessServiceImpl.java:115)
	at com.webank.ai.fate.api.eggroll.processor.ProcessServiceGrpc$MethodHandlers.invoke(ProcessServiceGrpc.java:626)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Throwable: idx: 0
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.webank.ai.fate.eggroll.roll.api.grpc.client.EggProcessServiceClient.unaryProcessToStorageLocatorUnaryCall(EggProcessServiceClient.java:146)
	at com.webank.ai.fate.eggroll.roll.api.grpc.client.EggProcessServiceClient.mapValues(EggProcessServiceClient.java:57)
	at com.webank.ai.fate.eggroll.roll.service.async.processor.MapValuesServiceProcessor.call(MapValuesServiceProcessor.java:35)
	at com.webank.ai.fate.eggroll.roll.service.async.processor.MapValuesServiceProcessor.call(MapValuesServiceProcessor.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at com.webank.ai.fate.core.api.grpc.client.GrpcStreamingClientTemplate.calleeStreamingRpcWithImmediateDelayedResult(GrpcStreamingClientTemplate.java:155)
	at com.webank.ai.fate.eggroll.roll.api.grpc.client.EggProcessServiceClient.unaryProcessToStorageLocatorUnaryCall(EggProcessServiceClient.java:144)
	... 7 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	... 3 more
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: 拒绝连接: /172.16.0.9:50001
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: java.net.ConnectException: 拒绝连接
	... 11 more

	at com.webank.ai.fate.core.error.exception.MultipleRuntimeThrowables.<init>(MultipleRuntimeThrowables.java:32)
	... 12 more
"
	debug_error_string = "{"created":"@1561360075.560867908","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"172.16.0.9:8011: com.webank.ai.fate.core.error.exception.MultipleRuntimeThrowables: error occured in sub tasks. processor type: MapValuesServiceProcessor\n\tat com.webank.ai.fate.eggroll.roll.api.grpc.server.RollProcessServiceImpl$ProcessServiceTemplate.run(RollProcessServiceImpl.java:324)\n\tat com.webank.ai.fate.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:51)\n\tat com.webank.ai.fate.eggroll.roll.api.grpc.server.RollProcessServiceImpl.mapValues(RollProcessServiceImpl.java:115)\n\tat com.webank.ai.fate.api.eggroll.processor.ProcessServiceGrpc$MethodHandlers.invoke(ProcessServiceGrpc.java:626)\n\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)\n\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)\n\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)\n\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\n\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.Throwable: idx: 0\njava.lang.RuntimeException: java.lang.reflect.InvocationTargetException\n\tat com.webank.ai.fate.eggroll.roll.api.grpc.client.EggProcessServiceClient.unaryProcessToStorageLocatorUnaryCall(EggProcessServiceClient.java:146)\n\tat com.webank.ai.fate.eggroll.roll.api.grpc.client.EggProcessServiceClient.mapValues(EggProcessServiceClient.java:57)\n\tat com.webank.ai.fate.eggroll.roll.service.async.processor.MapValuesServiceProcessor.call(MapValuesServiceProcessor.java:35)\n\tat com.webank.ai.fate.eggroll.roll.service.async.processor.MapValuesServiceProcessor.call(MapValuesServiceProcessor.java:26)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.reflect.InvocationTargetException\n\tat com.webank.ai.fate.core.api.grpc.client.GrpcStreamingClientTemplate.calleeStreamingRpcWithImmediateDelayedResult(GrpcStreamingClientTemplate.java:155)\n\tat com.webank.ai.fate.eggroll.roll.api.grpc.client.EggProcessServiceClient.unaryProcessToStorageLocatorUnaryCall(EggProcessServiceClient.java:144)\n\t... 7 more\nCaused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception\n\tat io.grpc.Status.asRuntimeException(Status.java:526)\n\tat io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)\n\tat io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)\n\tat io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)\n\tat io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)\n\tat io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)\n\tat io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)\n\tat io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)\n\tat io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)\n\tat io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)\n\tat io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)\n\tat io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)\n\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\n\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\n\t... 3 more\nCaused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: \u00e6\u008b\u0092\u00e7\u00bb\u009d\u00e8\u00bf\u009e\u00e6\u008e\u00a5: /172.16.0.9:50001\n\tat sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)\n\tat sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)\n\tat io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)\n\tat io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)\n\tat io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)\n\tat io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)\n\tat io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)\n\tat io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)\n\tat io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)\n\tat io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\t... 1 more\nCaused by: java.net.ConnectException: \u00e6\u008b\u0092\u00e7\u00bb\u009d\u00e8\u00bf\u009e\u00e6\u008e\u00a5\n\t... 11 more\n\n\n\n\tat com.webank.ai.fate.core.error.exception.MultipleRuntimeThrowables.<init>(MultipleRuntimeThrowables.java:32)\n\t... 12 more\n","grpc_status":13}"
>
"

**Comment by zengjice** [comment]
Please check the 50001 port on the 172.16.0.9 and check if the processor is successfully started.
You can refer to processor.sh in the cluster-deploy/example-dir-tree/python directory.
Thanks.

**Comment by sukkiCat** [comment]
grpc server failed to start because of python env. thx

**Comment by willysys** [comment]
> grpc server failed to start because of python env. thx

I also have the same error, how to run grpc server correctly?
