### ISSUE TITLE
input_data.mapValues() returns null result in cluster deploy mode

### ISSUE THREAD

**Issue by hosea1008** [WeBankFinTech/FATE#262]
**Describe the bug**
In line 101 of file `federatedml/util/data_io.py`, the input_data.mapValues(lambda ...) returns an empty `_DTable`. This function is supposed to split the str value of `input_data` as it does in standalone mode.

This line seems to publish tasks in the MySQL server and wait for `egg`s to finished the tasks. But when I turn to MySQL, the `task` table is empty. The `job_info` and `job_queue` table in database `task_manager` is also empty.

No error logs found in egg's and roll's log file. The `status_tracer_decorator.log` reports NoneType error (because of the empty `_DTable` returned by `mapValues(...)`)

**To Reproduce**
1. Deploy all services as suggested in the cluster-deploy instructions.
2. Breakpoint debuging `hetero_host_workflow.py`, step into `gen_data_instance` then step into `reader.read_data`
3. After loading input data in line 79 of `federatedml/util/data_io.py`, you can find that the input data are already loaded in `input_data`.
4. After line 101 `input_data_features = input_data.mapValues(...)`, evaluate `list(input_data_features.collect())` and you can find an empty result, while evaluating this to the `input_data` instance you can find the `input_data` is filled with values.

**Expected behavior**
It is expected to show the splited values as it was in standalone deployment mode.

**Desktop (please complete the following information):**
 - OS: Ubuntu server 18.04
 - Python 3.6
 - grpc 1.19

I am wondering where can I locate the bug and how can I fix it. Thanks!

> status_tracer_decorator.log

```
"2019-06-28 18:24:36,877 - status_tracer_decorator.py[line:74] - INFO: Traceback (most recent call last):
  File "/home/FATE/workflow/status_tracer_decorator.py", line 69, in wrapper
    res = func(self, *args, **kwargs)
  File "/home/FATE/workflow/workflow.py", line 690, in run
    self.workflow_param.train_input_namespace)
  File "/home/FATE/workflow/workflow.py", line 611, in gen_data_instance
    mode=mode)
  File "/home/FATE/federatedml/util/data_io.py", line 104, in read_data
    data_instance = self.fit(input_data_features, input_data_labels, table_name, namespace)
  File "/home/FATE/federatedml/util/data_io.py", line 113, in fit
    input_data_features = self.fill_missing_value(input_data_features, "fit")
  File "/home/FATE/federatedml/util/data_io.py", line 136, in fill_missing_value
    replace_value=self.default_value)
  File "/home/FATE/federatedml/feature/imputer.py", line 320, in fit
    process_data, replace_value = self.__replace(data, replace_method, replace_value, output_format)
  File "/home/FATE/federatedml/feature/imputer.py", line 277, in __replace
    replace_value = [replace_value for _ in range(shape)]
TypeError: 'NoneType' object cannot be interpreted as an integer
"
```

**Comment by mgqa34** [comment]
Can you please give more information about roll logs ? The logs are in roll/logs/fate-roll.log

**Comment by hosea1008** [comment]
Thanks for replying, sure thing, the roll log is attached as below:

[fate-roll.log](https://github.com/WeBankFinTech/FATE/files/3339025/fate-roll.log)

**Comment by mgqa34** [comment]
Thanks, we need another log to locate the error,  roll/logs/error.log,  sorry to trouble you again.

**Comment by hosea1008** [comment]
When a task is started and until exit, the error.log is empty. And it remain empty for a while after the task exits. Some WARNING appears in error.log about 20 minites after the task exits. (Seems not causing by the task itself)

The error.log is as follow:

```
Jun 28, 2019 10:42:36 AM io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler$3 onGoAwayReceived
WARNING: Received GOAWAY with ENHANCE_YOUR_CALM. Debug data: {1}
Jun 28, 2019 10:42:36 AM io.grpc.internal.AtomicBackoff$State backoff
WARNING: Increased keepalive time nanos to 720,000,000,000
Jun 28, 2019 10:42:36 AM io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler$3 onGoAwayReceived
WARNING: Received GOAWAY with ENHANCE_YOUR_CALM. Debug data: {1}
Jun 28, 2019 10:42:36 AM io.grpc.internal.AtomicBackoff$State backoff
WARNING: Increased keepalive time nanos to 720,000,000,000
Jun 28, 2019 10:48:36 AM io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler$3 onGoAwayReceived
WARNING: Received GOAWAY with ENHANCE_YOUR_CALM. Debug data: {1}
Jun 28, 2019 10:48:36 AM io.grpc.internal.AtomicBackoff$State backoff
WARNING: Increased keepalive time nanos to 720,000,000,000
Jun 28, 2019 10:48:36 AM io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler$3 onGoAwayReceived
WARNING: Received GOAWAY with ENHANCE_YOUR_CALM. Debug data: {1}
Jun 28, 2019 10:48:36 AM io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler$3 onGoAwayReceived
WARNING: Received GOAWAY with ENHANCE_YOUR_CALM. Debug data: {1}
Jun 28, 2019 10:48:36 AM io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler$3 onGoAwayReceived
WARNING: Received GOAWAY with ENHANCE_YOUR_CALM. Debug data: {1}
Jun 28, 2019 10:48:36 AM io.grpc.internal.AtomicBackoff$State backoff
WARNING: Increased keepalive time nanos to 720,000,000,000
Jun 28, 2019 10:48:36 AM io.grpc.internal.AtomicBackoff$State backoff
WARNING: Increased keepalive time nanos to 720,000,000,000
Jun 28, 2019 10:48:36 AM io.grpc.internal.AtomicBackoff$State backoff
WARNING: Increased keepalive time nanos to 720,000,000,000
Jun 28, 2019 10:48:36 AM io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler$3 onGoAwayReceived
WARNING: Received GOAWAY with ENHANCE_YOUR_CALM. Debug data: {1}
Jun 28, 2019 10:48:36 AM io.grpc.internal.AtomicBackoff$State backoff
WARNING: Increased keepalive time nanos to 720,000,000,000

```

**Comment by hosea1008** [comment]
Thanks for your replying again, could you please offer some details about what happens after `input_data.mapValues(...)` called in cluster mode? I think it would help me better understanding FATE. Thanks in advanced!

**Comment by hosea1008** [comment]
And some additional info for your reference, all services have been started and standby in the background, as shown in the following:

```
(FATE) user@ubuntu-18-04:~$ ps -aux | grep java
user   27091  0.1  2.5 4640052 211284 ?      Sl   18:02   0:09 java -cp conf/:lib/*:fate-federation.jar com.webank.ai.fate.driver.Federation -c conf/federation.properties
user   27120  0.2  3.5 5315800 287520 ?      Sl   18:02   0:18 java -cp conf/:lib/*:fate-meta-service.jar com.webank.ai.fate.eggroll.MetaService -c conf/meta-service.properties
user   27155  0.1  2.9 5572048 237900 ?      Sl   18:02   0:09 java -cp conf/:lib/*:fate-egg.jar com.webank.ai.fate.eggroll.Egg -c conf/egg.properties
user   27189  0.2  3.4 5789276 282948 ?      Sl   18:02   0:16 java -cp conf/:lib/*:fate-roll.jar com.webank.ai.fate.eggroll.Roll -c conf/roll.properties
user   27231  0.1  1.7 4833004 142716 ?      Sl   18:02   0:07 java -cp conf/:lib/*:fate-proxy.jar com.webank.ai.fate.networking.Proxy -c conf/proxy.properties
user   31061  0.0  0.0  13136  1008 pts/0    S+   20:14   0:00 grep --color=auto java
(FATE) user@ubuntu-18-04:~$ netstat -tupln | grep java
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::8011                 :::*                    LISTEN      27189/java
tcp6       0      0 :::8590                 :::*                    LISTEN      27120/java
tcp6       0      0 :::7888                 :::*                    LISTEN      27155/java
tcp6       0      0 :::9394                 :::*                    LISTEN      27091/java
(FATE) user@ubuntu-18-04:~$ netstat -tupln | grep python
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:9380            0.0.0.0:*               LISTEN      27452/python
tcp6       0      0 :::9360                 :::*                    LISTEN      27452/python
tcp6       0      0 :::50001                :::*                    LISTEN      11293/python
tcp6       0      0 :::50002                :::*                    LISTEN      11307/python
tcp6       0      0 :::50003                :::*                    LISTEN      11309/python
tcp6       0      0 :::50004                :::*                    LISTEN      11311/python
```

**Comment by maxwong** [comment]
Can you provide the followings:

**Comment by hosea1008** [comment]
1. Running `ps aux ...`:

```
(FATE) user@ubuntu-18-04:~$ ps aux | grep processor.py | grep -v grep
user   11293  0.0  0.9 1028116 74436 ?       Sl   Jun27   0:21 python /home/user/FATE/python/arch/processor/processor.py -p 50001 -d /home/user/FATE/data-dir
user   11307  0.0  0.9 1028116 74444 ?       Sl   Jun27   0:20 python /home/user/FATE/python/arch/processor/processor.py -p 50002 -d /home/user/FATE/data-dir
user   11309  0.0  0.9 1028116 78016 ?       Sl   Jun27   0:20 python /home/user/FATE/python/arch/processor/processor.py -p 50003 -d /home/user/FATE/data-dir
user   11311  0.0  0.9 1028116 80748 ?       Sl   Jun27   0:21 python /home/user/FATE/python/arch/processor/processor.py -p 50004 -d /home/user/FATE/data-dir
```

2. Executing the python code returns an empty list [].

3. `lsof -i:7778`:

```
(FATE) user@ubuntu-18-04:~/FATE$ lsof -i:7778
COMMAND     PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
java      27189 user  133u  IPv6 988801      0t0  TCP node1:41118->node1:7778 (ESTABLISHED)
storage-s 27267 user    5u  IPv6 948124      0t0  TCP *:7778 (LISTEN)
storage-s 27267 user    9u  IPv6 989793      0t0  TCP node1:7778->node1:41118 (ESTABLISHED)
```

And the `roll/logs/error.log` have nothing new, new logs in `roll/logs/fate-roll.log` are as follow:

```
[INFO ] 2019-06-28T12:22:43,979 [grpcServiceExecutor-19] [RollKvServiceImpl:113] - Kv.createIfAbsent request received. request: {"storageLocator":{"type":"LMDB","namespace":"a","name":"__federation__","fragment":0},"fragmentCount":10}
[INFO ] 2019-06-28T12:22:43,981 [grpcServiceExecutor-19] [BaseCrudClient:95] - [COMMON] invalid channel. status: SHUTDOWN
[INFO ] 2019-06-28T12:22:43,981 [pool-3-thread-15] [GrpcChannelFactory:79] - [COMMON][CHANNEL][REMOVE] removed for ip: node1, port: 7778, hostname: . reason: EXPIRED
[INFO ] 2019-06-28T12:22:43,982 [pool-3-thread-15] [GrpcChannelFactory:85] - [COMMON][CHANNEL][REMOVE] removed channel state: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:22:43,983 [pool-3-thread-15] [GrpcChannelFactory:108] - [COMMON][CHANNEL][CREATE] creating insecure channel for endpoint: ip: node1, port: 8590, hostname: 
[INFO ] 2019-06-28T12:22:43,983 [pool-3-thread-15] [GrpcChannelFactory:200] - [COMMON][CHANNEL][CREATE] creating channel to {"ip":"node1","port":8590,"hostname":""}, isSecure: false
[INFO ] 2019-06-28T12:22:43,984 [pool-3-thread-15] [GrpcChannelFactory:230] - [COMMON][CHANNEL][CREATE] created channel to {"ip":"node1","port":8590,"hostname":""}, isSecure: false
[INFO ] 2019-06-28T12:22:43,985 [grpcServiceExecutor-19] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:22:52,574 [grpcServiceExecutor-19] [RollKvServiceImpl:113] - Kv.createIfAbsent request received. request: {"storageLocator":{"type":"IN_MEMORY","namespace":"a","name":"735b7222-999f-11e9-b797-005056bbda3d","fragment":0},"fragmentCount":2}
[WARN ] 2019-06-28T12:22:52,600 [grpcServiceExecutor-19] [StoreInfo:45] - no fragment in store info
[INFO ] 2019-06-28T12:22:52,601 [grpcServiceExecutor-19] [RollKvServiceImpl:178] - Kv.putAll request received: ["com.webank.ai.fate.core.io.StoreInfo",{"type":"IN_MEMORY","nameSpace":"a","tableName":"735b7222-999f-11e9-b797-005056bbda3d"}]
[INFO ] 2019-06-28T12:22:52,601 [grpcServiceExecutor-19] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:22:52,602 [grpcServiceExecutor-19] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:22:52,602 [grpcServiceExecutor-19] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:22:52,625 [asyncThreadPool-49] [StorageServiceClient:120] - [ROLL][PUTALL][SUBTASK] putAll subTask request received: ["com.webank.ai.fate.core.io.StoreInfo",{"type":"IN_MEMORY","nameSpace":"a","tableName":"735b7222-999f-11e9-b797-005056bbda3d","fragment":1}]
[INFO ] 2019-06-28T12:22:52,628 [pool-3-thread-15] [GrpcChannelFactory:108] - [COMMON][CHANNEL][CREATE] creating insecure channel for endpoint: ip: node1, port: 7778, hostname: 
[INFO ] 2019-06-28T12:22:52,629 [pool-3-thread-15] [GrpcChannelFactory:200] - [COMMON][CHANNEL][CREATE] creating channel to {"ip":"node1","port":7778,"hostname":""}, isSecure: false
[INFO ] 2019-06-28T12:22:52,629 [pool-3-thread-15] [GrpcChannelFactory:230] - [COMMON][CHANNEL][CREATE] created channel to {"ip":"node1","port":7778,"hostname":""}, isSecure: false
[INFO ] 2019-06-28T12:22:52,630 [asyncThreadPool-49] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:22:52,631 [asyncThreadPool-50] [StorageServiceClient:120] - [ROLL][PUTALL][SUBTASK] putAll subTask request received: ["com.webank.ai.fate.core.io.StoreInfo",{"type":"IN_MEMORY","nameSpace":"a","tableName":"735b7222-999f-11e9-b797-005056bbda3d","fragment":0}]
[INFO ] 2019-06-28T12:22:52,634 [asyncThreadPool-50] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:22:52,637 [asyncThreadPool-50] [StorageKvPutAllRequestStreamProcessor:65] - [PUTALL][SUBTASK] actual completes putAll sub task. remaining: 0, entryCount: 5
[ERROR] 2019-06-28T12:22:52,646 [asyncThreadPool-50] [PutAllProcessorListenableFutureCallback:79] - [ROLL][KV][PUTALL][ONSUCCESS] put all success. storeInfo: StoreInfo(type=IN_MEMORY, nameSpace=a, tableName=735b7222-999f-11e9-b797-005056bbda3d, fragment=0), latch count: 2, address: node1:7778
[INFO ] 2019-06-28T12:22:52,682 [asyncThreadPool-49] [StorageKvPutAllRequestStreamProcessor:65] - [PUTALL][SUBTASK] actual completes putAll sub task. remaining: 0, entryCount: 5
[ERROR] 2019-06-28T12:22:52,691 [asyncThreadPool-49] [PutAllProcessorListenableFutureCallback:79] - [ROLL][KV][PUTALL][ONSUCCESS] put all success. storeInfo: StoreInfo(type=IN_MEMORY, nameSpace=a, tableName=735b7222-999f-11e9-b797-005056bbda3d, fragment=1), latch count: 1, address: node1:7778
[INFO ] 2019-06-28T12:22:52,692 [grpcServiceExecutor-19] [RollKvPutAllServerRequestStreamObserver:212] - [ROLL][KV][PUTALL] waiting put all to finish. storeInfo: StoreInfo(type=IN_MEMORY, nameSpace=a, tableName=735b7222-999f-11e9-b797-005056bbda3d, fragment=null), current latch count: 0, finished count: 2
[INFO ] 2019-06-28T12:22:52,692 [grpcServiceExecutor-19] [RollKvPutAllServerRequestStreamObserver:232] - [ROLL][PROCESS][PUTALL] put all completed. storeInfo: StoreInfo(type=IN_MEMORY, nameSpace=a, tableName=735b7222-999f-11e9-b797-005056bbda3d, fragment=null), totalCount: 10
[INFO ] 2019-06-28T12:23:00,506 [grpcServiceExecutor-19] [RollProcessServiceImpl:113] - [ROLL][PROCESS][MapValues] request received: {"info":{"task_id":"a","function_id":"7815d028-999f-11e9-b797-005056bbda3d","function_bytes":"gASVEgEAAAAAAACMGmFyY2guYXBpLnV0aWxzLmNsb3VkcGlja2xllIwOX2ZpbGxfZnVuY3Rpb26Uk5QoaACMD19tYWtlX3NrZWxfZnVuY5STlGgAjA1fYnVpbHRpbl90eXBllJOUjAhDb2RlVHlwZZSFlFKUKEsBSwBLAUsCS0NDCHwAZAEXAFMAlE5LAYaUKYwBdpSFlIwHPHN0ZGluPpSMCDxsYW1iZGE+lEsBQwCUKSl0lFKUSv////99lIeUUpR9lCiMB2dsb2JhbHOUfZSMCGRlZmF1bHRzlE6MBGRpY3SUfZSMBm1vZHVsZZSMCF9fbWFpbl9flIwOY2xvc3VyZV92YWx1ZXOUTowIcXVhbG5hbWWUaA91dFIu"},"operand":{"type":"IN_MEMORY","namespace":"a","name":"735b7222-999f-11e9-b797-005056bbda3d","fragment":0}}
[INFO ] 2019-06-28T12:23:00,507 [grpcServiceExecutor-19] [RollProcessServiceImpl:238] - [ROLL][PROCESS][ProcessServiceTemplate] requestStorageLocator: {"type":"IN_MEMORY","namespace":"a","name":"735b7222-999f-11e9-b797-005056bbda3d","fragment":0}
[INFO ] 2019-06-28T12:23:00,507 [grpcServiceExecutor-19] [BaseCrudClient:95] - [COMMON] invalid channel. status: SHUTDOWN
[INFO ] 2019-06-28T12:23:00,508 [grpcServiceExecutor-19] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:23:00,513 [grpcServiceExecutor-19] [BaseCrudClient:95] - [COMMON] invalid channel. status: SHUTDOWN
[INFO ] 2019-06-28T12:23:00,513 [grpcServiceExecutor-19] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:23:00,523 [grpcServiceExecutor-19] [RollProcessServiceImpl:268] - [ROLL][PROCESS][ProcessServiceTemplate] storeInfoWithFragment: StoreInfo(type=IN_MEMORY, nameSpace=a, tableName=735b7222-999f-11e9-b797-005056bbda3d, fragment=0), fragmentNodeId: 4, storageNode: Node [Hash = -1659922994, nodeId=4, host=null, ip=node1, port=7778, type=STORAGE, status=HEALTHY, lastHeartbeatAt=null, createdAt=Fri Jun 28 16:37:21 UTC 2019, updatedAt=Fri Jun 28 16:37:21 UTC 2019], target: node1
[INFO ] 2019-06-28T12:23:00,527 [pool-3-thread-15] [GrpcChannelFactory:108] - [COMMON][CHANNEL][CREATE] creating insecure channel for endpoint: ip: node1, port: 7888, hostname: 
[INFO ] 2019-06-28T12:23:00,527 [pool-3-thread-15] [GrpcChannelFactory:200] - [COMMON][CHANNEL][CREATE] creating channel to {"ip":"node1","port":7888,"hostname":""}, isSecure: false
[INFO ] 2019-06-28T12:23:00,528 [pool-3-thread-15] [GrpcChannelFactory:230] - [COMMON][CHANNEL][CREATE] created channel to {"ip":"node1","port":7888,"hostname":""}, isSecure: false
[INFO ] 2019-06-28T12:23:00,530 [grpcServiceExecutor-19] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:23:00,542 [grpcServiceExecutor-19] [RollProcessServiceImpl:268] - [ROLL][PROCESS][ProcessServiceTemplate] storeInfoWithFragment: StoreInfo(type=IN_MEMORY, nameSpace=a, tableName=735b7222-999f-11e9-b797-005056bbda3d, fragment=1), fragmentNodeId: 4, storageNode: Node [Hash = -1659922994, nodeId=4, host=null, ip=node1, port=7778, type=STORAGE, status=HEALTHY, lastHeartbeatAt=null, createdAt=Fri Jun 28 16:37:21 UTC 2019, updatedAt=Fri Jun 28 16:37:21 UTC 2019], target: node1
[INFO ] 2019-06-28T12:23:00,543 [pool-3-thread-15] [GrpcChannelFactory:79] - [COMMON][CHANNEL][REMOVE] removed for ip: 10.44.12.49, port: 50004, hostname: . reason: EXPIRED
[INFO ] 2019-06-28T12:23:00,543 [pool-3-thread-15] [GrpcChannelFactory:85] - [COMMON][CHANNEL][REMOVE] removed channel state: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:23:00,543 [pool-3-thread-15] [GrpcChannelFactory:79] - [COMMON][CHANNEL][REMOVE] removed for ip: 10.44.12.49, port: 50001, hostname: . reason: EXPIRED
[INFO ] 2019-06-28T12:23:00,543 [grpcServiceExecutor-19] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:23:00,543 [pool-3-thread-15] [GrpcChannelFactory:85] - [COMMON][CHANNEL][REMOVE] removed channel state: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:23:00,543 [pool-3-thread-15] [GrpcChannelFactory:79] - [COMMON][CHANNEL][REMOVE] removed for ip: 10.44.12.49, port: 50003, hostname: . reason: EXPIRED
[INFO ] 2019-06-28T12:23:00,543 [pool-3-thread-15] [GrpcChannelFactory:85] - [COMMON][CHANNEL][REMOVE] removed channel state: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:23:00,544 [pool-3-thread-15] [GrpcChannelFactory:108] - [COMMON][CHANNEL][CREATE] creating insecure channel for endpoint: ip: 10.44.12.49, port: 50004, hostname: 
[INFO ] 2019-06-28T12:23:00,544 [pool-3-thread-15] [GrpcChannelFactory:200] - [COMMON][CHANNEL][CREATE] creating channel to {"ip":"10.44.12.49","port":50004,"hostname":""}, isSecure: false
[INFO ] 2019-06-28T12:23:00,544 [pool-3-thread-15] [GrpcChannelFactory:230] - [COMMON][CHANNEL][CREATE] created channel to {"ip":"10.44.12.49","port":50004,"hostname":""}, isSecure: false
[INFO ] 2019-06-28T12:23:00,545 [asyncThreadPool-49] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:23:00,554 [pool-3-thread-15] [GrpcChannelFactory:108] - [COMMON][CHANNEL][CREATE] creating insecure channel for endpoint: ip: 10.44.12.49, port: 50001, hostname: 
[INFO ] 2019-06-28T12:23:00,555 [pool-3-thread-15] [GrpcChannelFactory:200] - [COMMON][CHANNEL][CREATE] creating channel to {"ip":"10.44.12.49","port":50001,"hostname":""}, isSecure: false
[INFO ] 2019-06-28T12:23:00,555 [pool-3-thread-15] [GrpcChannelFactory:230] - [COMMON][CHANNEL][CREATE] created channel to {"ip":"10.44.12.49","port":50001,"hostname":""}, isSecure: false
[INFO ] 2019-06-28T12:23:00,557 [asyncThreadPool-49] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:23:00,562 [grpcServiceExecutor-19] [RollProcessServiceImpl:312] - [ROLL][PROCESS][ProcessServiceTemplate] valid result. ready to return storeInfo: StoreInfo(type=IN_MEMORY, nameSpace=a, tableName=735b7222-999f-11e9-b797-005056bbda3d, fragment=0), processType: MapValuesServiceProcessor
[INFO ] 2019-06-28T12:23:00,562 [grpcServiceExecutor-19] [ProcessServiceStorageLocatorResultHandler:41] - [HANDLE][RESULT] {"type":"IN_MEMORY","namespace":"a","name":"7815d028-999f-11e9-b797-005056bbda3d","fragment":0}, unprocessedResults.size: 2
[INFO ] 2019-06-28T12:23:00,564 [grpcServiceExecutor-19] [RollKvServiceImpl:113] - Kv.createIfAbsent request received. request: {"storageLocator":{"type":"IN_MEMORY","namespace":"a","name":"7815d028-999f-11e9-b797-005056bbda3d","fragment":0},"fragmentCount":2}
[WARN ] 2019-06-28T12:23:11,178 [grpcServiceExecutor-19] [StoreInfo:45] - no fragment in store info
[INFO ] 2019-06-28T12:23:11,179 [grpcServiceExecutor-19] [RollKvServiceImpl:230] - Kv.iterate request received: ["com.webank.ai.fate.core.io.StoreInfo",{"type":"IN_MEMORY","nameSpace":"a","tableName":"7815d028-999f-11e9-b797-005056bbda3d"}]
[INFO ] 2019-06-28T12:23:11,180 [grpcServiceExecutor-19] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:23:11,180 [grpcServiceExecutor-19] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:23:11,192 [asyncThreadPool-49] [IterateProcessor:123] - [ROLL][ITERATOR][PROCESSOR] final minChunkSize: 4194304
[INFO ] 2019-06-28T12:23:11,193 [asyncThreadPool-49] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:23:11,195 [asyncThreadPool-49] [IterateProcessor:270] - [ROLL][KV][ITERATE][PROCESSOR] waiting latch for: StoreInfo(type=IN_MEMORY, nameSpace=a, tableName=7815d028-999f-11e9-b797-005056bbda3d, fragment=0)
[INFO ] 2019-06-28T12:23:11,195 [asyncThreadPool-49] [IterateProcessor:275] - [ROLL][KV][ITERATE][PROCESSOR] broker: StoreInfo(type=IN_MEMORY, nameSpace=a, tableName=7815d028-999f-11e9-b797-005056bbda3d, fragment=0), closable: true, ready: false
[INFO ] 2019-06-28T12:23:11,196 [asyncThreadPool-49] [IterateProcessor:284] - [ROLL][KV][ITERATE][PROCESSOR] data arrived. size: 0, fragment order: 0, node address: node1:7778, range start: , range end: 
[INFO ] 2019-06-28T12:23:11,196 [asyncThreadPool-49] [GrpcStubFactory:41] - [CORE] create stub. channel status: isShutdown: false, isTerminated: false
[INFO ] 2019-06-28T12:23:11,197 [asyncThreadPool-49] [IterateProcessor:270] - [ROLL][KV][ITERATE][PROCESSOR] waiting latch for: StoreInfo(type=IN_MEMORY, nameSpace=a, tableName=7815d028-999f-11e9-b797-005056bbda3d, fragment=1)
[INFO ] 2019-06-28T12:23:11,198 [asyncThreadPool-49] [IterateProcessor:275] - [ROLL][KV][ITERATE][PROCESSOR] broker: StoreInfo(type=IN_MEMORY, nameSpace=a, tableName=7815d028-999f-11e9-b797-005056bbda3d, fragment=1), closable: true, ready: false
[INFO ] 2019-06-28T12:23:11,198 [asyncThreadPool-49] [IterateProcessor:284] - [ROLL][KV][ITERATE][PROCESSOR] data arrived. size: 0, fragment order: 1, node address: node1:7778, range start: , range end: 
[INFO ] 2019-06-28T12:23:11,198 [asyncThreadPool-49] [RollKvServiceImpl:249] - [ROLL][KV][ITERATE] finished without error. storeInfo: StoreInfo(type=IN_MEMORY, nameSpace=a, tableName=7815d028-999f-11e9-b797-005056bbda3d, fragment=null), request: {"start":"","end":"","minChunkSize":"0"}
[INFO ] 2019-06-28T12:23:11,198 [grpcServiceExecutor-19] [RollKvServiceImpl:283] - [ROLL][KV][ITERATE] roll iterate successfully. totalIterated: 0, storeInfo: StoreInfo(type=IN_MEMORY, nameSpace=a, tableName=7815d028-999f-11e9-b797-005056bbda3d, fragment=null), request: {"start":"","end":"","minChunkSize":"0"}

```

**Comment by hosea1008** [comment]
Duplicate of #276
