### ISSUE TITLE
Minimization testing issue

### ISSUE THREAD

**Issue by wwwwww1020** [WeBankFinTech/FATE#267]
When I just run this command 'sh run.sh host fast ', there is a stuck like 

role is host
task is fast
Traceback (most recent call last):
  File "/data/projects/fate/python/examples/min_test_task/run_task.py", line 455, in <module>
    data_file)
  File "/data/projects/fate/python/examples/min_test_task/run_task.py", line 137, in import_id_library
    stdout = exec_task(json_info, "upload", role)
  File "/data/projects/fate/python/examples/min_test_task/run_task.py", line 72, in exec_task
    stdout = json.loads(stdout)
  File "/home/mi/anaconda3/envs/FATE/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/mi/anaconda3/envs/FATE/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/mi/anaconda3/envs/FATE/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
finish upload intersect data
{'file': '/data/projects/fate/python/examples/min_test_task/../data/breast_a.csv', 'head': 1, 'partition': 10, 'gen_table_info': True, 'local': {'party_id': 10000, 'role': 'host'}, 'role': {'guest': [9999], 'host': [10000], 'arbiter': [10000]}, 'data_type': 'train_input'}
Traceback (most recent call last):
  File "/data/projects/fate/python/examples/min_test_task/run_task.py", line 458, in <module>
    data_file, data_type)
  File "/data/projects/fate/python/examples/min_test_task/run_task.py", line 164, in upload
    stdout = exec_task(json_info, "upload", role)
  File "/data/projects/fate/python/examples/min_test_task/run_task.py", line 72, in exec_task
    stdout = json.loads(stdout)
  File "/home/mi/anaconda3/envs/FATE/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/mi/anaconda3/envs/FATE/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/mi/anaconda3/envs/FATE/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
finish upload train data
{'file': '/data/projects/fate/python/examples/min_test_task/../data/breast_a.csv', 'head': 1, 'partition': 10, 'gen_table_info': True, 'local': {'party_id': 10000, 'role': 'host'}, 'role': {'guest': [9999], 'host': [10000], 'arbiter': [10000]}, 'data_type': 'predict_input'}
Traceback (most recent call last):
  File "/data/projects/fate/python/examples/min_test_task/run_task.py", line 458, in <module>
    data_file, data_type)
  File "/data/projects/fate/python/examples/min_test_task/run_task.py", line 164, in upload
    stdout = exec_task(json_info, "upload", role)
  File "/data/projects/fate/python/examples/min_test_task/run_task.py", line 72, in exec_task
    stdout = json.loads(stdout)
  File "/home/mi/anaconda3/envs/FATE/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/mi/anaconda3/envs/FATE/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/mi/anaconda3/envs/FATE/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
finish upload predict data
*********************
*******finish!*******

actually I can run successful for the stand alone testing but the minimization testing has this problem. Why is that, thank you.

**Comment by zazd** [comment]
please check this "ps -ef | grep task_manager" to find if the server of task_manager is running

**Comment by Tomposon** [comment]
Have you solved this problem? I came across the same issue. @wwwwww1020
