### ISSUE TITLE
bug when test FATE

### ISSUE THREAD

**Issue by nickzhou123** [WeBankFinTech/FATE#299]
bug report:
start to run test /fate/federatedml/test/../feature/test/quantile_binning_test.py
.E
======================================================================
ERROR: test_quantile_binning (__main__.TestQuantileBinningSpeed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/fate/federatedml/test/../feature/test/quantile_binning_test.py", line 140, in test_quantile_binning
    split_points = quan_bin.fit_split_points(self.table)
  File "/fate/federatedml/feature/binning/quantile_binning.py", line 76, in fit_split_points
    summary_dict = data_instances.mapPartitions(f)
  File "/fate/arch/api/standalone/eggroll.py", line 703, in mapPartitions
    results = self._submit_to_pool(func, do_map_partitions)
  File "/fate/arch/api/standalone/eggroll.py", line 687, in _submit_to_pool
    results.append(Standalone.get_instance().pool.submit(_do_func, _p))
  File "/usr/local/lib/python3.6/concurrent/futures/process.py", line 466, in submit
    self._start_queue_management_thread()
  File "/usr/local/lib/python3.6/concurrent/futures/process.py", line 427, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/local/lib/python3.6/concurrent/futures/process.py", line 446, in _adjust_process_count
    p.start()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
----------------------------------------------------------------------
Ran 2 tests in 14.053s

FAILED (errors=1)
start to run test /fate/federatedml/test/../feature/test/quantile_summaries_test.py
min_rank: 89800, found_rank: 89932, max_rank: 90200
.min_rank: 89800, found_rank: 90047, max_rank: 90200
min_rank: 89800, found_rank: 90045, max_rank: 90200
min_rank: 89800, found_rank: 90033, max_rank: 90200
min_rank: 89800, found_rank: 89916, max_rank: 90200
min_rank: 89800, found_rank: 89979, max_rank: 90200
question:
how pass the error

**Comment by tanmc123** [comment]
This might cause by the data size in test case is too large. I will change it. Thanks for your report.
